language: go
go:
  - 1.8.x

go_import_path: github.com/lubinsz/libnetwork

# `make ci` uses Docker.
sudo: required
services:
  - docker


before_install:
#  - sudo apt-get -qq update
  - sudo modprobe ip_vs
 # - env | grep TRAVIS_

script:
  - make build 
  - make check 
