language: go
go:
  - 1.7.x
  - 1.8.x
  - 1.9.x

go_import_patch: github.com/docker/libnetwork

sudo: required

befor_install:
  - sudo modprobe ip_vs

service:
  - docker

script:
  - make check
  - make integration-tests
